#!/bin/bash
# smart_alarm
# Copyright (c) 2020, Joaquin G. Duo
# Code Licensed under LGPL License. See LICENSE file.

conf_file=/etc/salarm/global.conf

if [[ -e $conf_file ]];then
  source $conf_file
fi

if [[ $PIR_SERVER_DELAY_SEC != "" ]]; then
  sleep $PIR_SERVER_DELAY_SEC
fi

python3 -m smart_alarm.pir_server
