#!/bin/bash
# smart_alarm
# Copyright (c) 2020, Joaquin G. Duo
# Code Licensed under LGPL License. See LICENSE file.

conf_file=/etc/salarm/mail_server.conf

if [[ -e $conf_file ]];then
  source $conf_file
fi

python3 -m smart_alarm.mail_server
