#!/bin/bash
# smart_alarm
# Copyright (c) 2020, Joaquin G. Duo
# Code Licensed under LGPL License. See LICENSE file.

python3 -c 'from smart_alarm.cmds_commands import upload_web_client; upload_web_client()'
