#!/bin/bash
# smart_alarm
# Copyright (c) 2020, Joaquin G. Duo
# Code Licensed under LGPL License. See LICENSE file.

while test $# -gt 0; do
case "$1" in
    -A|--android-server)
    journalctl -u salarm_android_server.service -b
    shift
    ;;
    -C|--cmds-server)
    journalctl -u salarm_cmds_server.service -b
    shift
    ;;
    -M|--mail-server)
    journalctl -u salarm_mail_server.service -b
    shift
    ;;
    -a|--all)
    systemctl status salarm_android_server.service
    systemctl status salarm_cmds_server.service
    systemctl status salarm_mail_server.service
    shift
    ;;
    -h|--help)
    echo "$cmd_name [-a|--all] [-A|--android-server] [-M|--mail-server] [-h|--help]"
    echo "
Controlling:
    sudo systemctl start salarm_android_server.service
    sudo systemctl start salarm_cmds_server.service
    sudo systemctl start salarm_mail_server.service

    sudo systemctl restart salarm_android_server.service
    sudo systemctl restart salarm_cmds_server.service
    sudo systemctl restart salarm_mail_server.service
    
    sudo systemctl stop salarm_android_server.service
    sudo systemctl stop salarm_cmds_server.service
    sudo systemctl stop salarm_mail_server.service
"
    exit 0
    ;;
    *)
    break
    ;;
esac
done


