#!/bin/bash

STREAM_URL="$1"
SHOT_PATH=${2:-./$(/bin/date '+%d-%m-%Y__%H-%M-%S').jpg}

NO_S3_UPLOAD=$3


if [[ $STREAM_URL == "" ]]; then
  echo "Usage:
  $(basename $0) <URL> [image path]
  
  Takes an image from a ipcam and uploads it to S3
  "
  exit 1
fi

rm $SHOT_PATH > /dev/null

OUT_PATH=""
if ffmpeg -stimeout 2000000 -i $STREAM_URL -f image2 -vframes 1 -pix_fmt yuvj420p $SHOT_PATH ; then
  if [[ $NO_S3_UPLOAD == "" ]];then
    if aws s3 cp $SHOT_PATH s3://a.jduo.de/i/ --acl public-read --cache-control private ; then
      rm $SHOT_PATH
      OUT_PATH="https://a.jduo.de/i/$SHOT_PATH"
    fi
  else
    OUT_PATH="$SHOT_PATH"
  fi
fi

if [[ $OUT_PATH != "" ]]; then
  echo SUCCESS: $OUT_PATH
else
  echo ERROR
  exit 1
fi
