#!/bin/bash
# smart_alarm
# Copyright (c) 2020, Joaquin G. Duo
# Code Licensed under LGPL License. See LICENSE file.

DEPLOY_ANDROID_SCRIPTS_DIR=${DEPLOY_ANDROID_SCRIPTS_DIR:-/sdcard/qpython/scripts}
ANDROID_AUTH_TOKEN=${ANDROID_AUTH_TOKEN:-123}
QPYTHON_PATH=${QPYTHON_PATH:-/data/data/org.qpython.qpy/files/bin/qpython.sh}

FORCE_COPY=${FORCE_COPY:-0}
if [[ $* == *--foce-copy* ]]; then
  FORCE_COPY=1
fi

init_file="$(python3 -c 'import smart_alarm; print(smart_alarm.__path__[0])')"/android_init.py
server_file="$(python3 -c 'import smart_alarm; print(smart_alarm.__path__[0])')"/android_server.py
if [[ $* == *--test-init* ]]; then
    FORCE_COPY=$FORCE_COPY salarm_android_python -c $init_file
elif [[ $* == *--init* ]]; then
    FORCE_COPY=$FORCE_COPY salarm_android_python -c -s -d $init_file
    sleep 14
    salarm_android_python -c -d $init_file
    sleep 8
else
    echo adb forward tcp:8000 tcp:8000
    adb forward tcp:8000 tcp:8000
    FORCE_COPY=$FORCE_COPY salarm_android_python -c $server_file --adb
fi



